# services:
#   - type: web
#     name: osrm-backend
#     env: docker
#     plan: free
#     dockerfilePath: ./Dockerfile.osrm
#     autoDeploy: false
#     region: singapore
#     ports:
#       - port: 5000
#         protocol: http

# render.yaml
services:
  - type: web
    name: osrm-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    region: singapore
